services:
  frontend:
    build:
     context: .
     dockerfile: Dockerfile
    image: private-childcare-calendar-frontend:latest
    # image: ghcr.io/emilstorgaard/elines-krudtugler-frontend:latest
    container_name: elines_krudtugler_frontend
    ports:
      - '8082:3000'
    restart: unless-stopped